### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by tylerdiaz** [lee-dohm/bug-report#45]
Steps to repro:

1. Fresh install
2. `Cmd+Shift+P`
3. Insert version info.

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [bug-report](https://github.com/lee-dohm/bug-report) package, v0.5.5

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of null

```
At /Users/tylerdiaz/.atom/packages/bug-report/lib/bug-report.coffee:92

TypeError: Cannot read property 'toString' of null
  at BugReport.apmVersionInfo (/Users/tylerdiaz/.atom/packages/bug-report/lib/bug-report.coffee:92:41)
  at BugReport.apmVersionText (/Users/tylerdiaz/.atom/packages/bug-report/lib/bug-report.coffee:97:28)
  at BugReport.versionSection (/Users/tylerdiaz/.atom/packages/bug-report/lib/bug-report.coffee:195:8)
  at atom-workspace.commands.atom.commands.add.bug-report:insert-version-info (/Users/tylerdiaz/.atom/packages/bug-report/lib/bug-report.coffee:47:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Users/tylerdiaz/.atom/packages/bug-report/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Users/tylerdiaz/.atom/packages/bug-report/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -0:50.9 bug-report:open (atom-text-editor.editor.is-focused)
     -0:47.5 core:save (atom-text-editor.editor)
     -0:39.8 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.5 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:16.7 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:14.8 core:move-down (atom-text-editor.editor.is-focused)
     -0:14.3 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:13.7 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:12.9 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:11.6 core:confirm (atom-text-editor.editor.mini)
     -0:11.6 bug-report:open (atom-text-editor.editor.is-focused)
     -0:07.5 core:close (atom-text-editor.editor)
     -0:04.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.5 core:move-down (atom-text-editor.editor.mini)
     -0:02.0 core:confirm (atom-text-editor.editor.mini)
     -0:02.0 bug-report:insert-version-info (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "bookmarks",
      "background-tips",
      "feedback",
      "git-diff",
      "atomatigit",
      "color-picker",
      "remember-session",
      "metrics",
      "link",
      "project-manager",
      "jekyll",
      "cucumber",
      "term2",
      "markdown-writer"
    ],
    "themes": [
      "seti-ui",
      "railscast-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-spotify, v1.2.0
autocomplete-plus, v2.1.6
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.0.1
block-travel, v1.0.2
bug-report, v0.5.5
change-case, v0.4.0
circle-ci, v0.6.2
coffee-compile, v0.10.0
emmet, v2.3.3
git-log, v0.2.0
highlight-selected, v0.9.0
linter, v0.11.1
linter-coffeelint, v0.1.7
linter-rubocop, v0.2.1
linter-ruby, v0.1.4
project-ring, v0.19.3
railscast-theme, v0.2.0
react, v0.9.8
ruby-block, v0.2.2
ruby-slim, v0.2.0
set-syntax, v0.2.1
seti-ui, v0.6.3
terminal-panel, v1.9.2
white-cursor, v0.5.2

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Thanks, I'll take a look!
