### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by kierans** [lee-dohm/bug-report#50]
1. Open Bug Report (`Ctrl+Alt+Shift+B`); `bug-report.md` opens with an empty TextEditor, no custom panels at the bottom of the screen
![bug-report-editor](https://cloud.githubusercontent.com/assets/1179247/8320418/062707a8-1a5e-11e5-9450-581a65af583f.png)

2. Insert version info

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [bug-report](https://github.com/lee-dohm/bug-report) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At /Users/kieran/.atom/packages/bug-report/lib/bug-report.coffee:97

TypeError: Cannot read property 'trim' of undefined
    at BugReport.apmVersionText (/Users/kieran/.atom/packages/bug-report/lib/bug-report.coffee:87:33)
    at BugReport.versionSection (/Users/kieran/.atom/packages/bug-report/lib/bug-report.coffee:206:211)
    at atom-workspace.commands.atom.commands.add.bug-report:insert-version-info (/Users/kieran/.atom/packages/bug-report/lib/bug-report.coffee:53:61)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
```

### Commands

```
     -3:02.8.0 command-palette:toggle (atom-pane.pane.active)
     -3:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:01.6.0 bug-report:open (atom-pane.pane.active)
     -0:22.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:19.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:11.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:09.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:09.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:02.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 bug-report:insert-version-info (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/kieran/Projects"
  }
}
```

### Installed Packages

    $ apm --version
    apm  0.171.0
    npm  2.5.1
    node 0.10.35
    python 2.7.6
    git 2.4.2

    $ apm list -p -i
    /Users/kieran/.atom/packages (4)
    ├── bug-report@0.7.0
    ├── html-tab@1.0.2
    ├── symbol-gen@1.0.0
    └── term2@0.9.9

**Comment by lee-dohm** [comment]
Thanks for reporting!
